// <auto-generated />
using System;
using ItCareers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItCareers.Infrastructure.Migrations
{
    [DbContext(typeof(ItCareersDbContext))]
    [Migration("20260812102905_AddSpecializations")]
    partial class AddSpecializations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItCareers.Domain.Entities.CareerQuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CareerQuizQuestions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.CareerQuizSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RecommendedTrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedTrackId");

                    b.ToTable("CareerQuizSubmissions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LearnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.HasIndex("UserId", "RoadmapId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaddleTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaddleTransactionId")
                        .IsUnique();

                    b.HasIndex("RoadmapId");

                    b.HasIndex("UserId", "RoadmapId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.FinalExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("FinalExamAttempts");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.FinalExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("FinalExamQuestions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("PhaseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("Skills")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.PhaseCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("UserId", "PhaseId")
                        .IsUnique();

                    b.ToTable("PhaseCompletions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCapstone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PaddlePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PassThresholdPercent")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("SequentialUnlockEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TrackId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("DemandLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("IntroVideoDurationLabel")
                        .HasColumnType("text");

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedRoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfFileName")
                        .HasColumnType("text");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.CareerQuizQuestion", b =>
                {
                    b.OwnsMany("ItCareers.Domain.Entities.CareerQuizOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("CareerQuizQuestionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.HasKey("CareerQuizQuestionId", "__synthesizedOrdinal");

                            b1.ToTable("CareerQuizQuestions");

                            b1
                                .ToJson("Options")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CareerQuizQuestionId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b2 =>
                                {
                                    b2.Property<Guid>("CareerQuizOptionCareerQuizQuestionId");

                                    b2.Property<int>("CareerQuizOption__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("CareerQuizOptionCareerQuizQuestionId", "CareerQuizOption__synthesizedOrdinal");

                                    b2.ToTable("CareerQuizQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("CareerQuizOptionCareerQuizQuestionId", "CareerQuizOption__synthesizedOrdinal");
                                });

                            b1.OwnsMany("ItCareers.Domain.Entities.TrackWeight", "TrackWeights", b2 =>
                                {
                                    b2.Property<Guid>("CareerQuizOptionCareerQuizQuestionId");

                                    b2.Property<int>("CareerQuizOption__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("TrackId");

                                    b2.Property<int>("Weight");

                                    b2.HasKey("CareerQuizOptionCareerQuizQuestionId", "CareerQuizOption__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("CareerQuizQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("CareerQuizOptionCareerQuizQuestionId", "CareerQuizOption__synthesizedOrdinal");
                                });

                            b1.Navigation("Text")
                                .IsRequired();

                            b1.Navigation("TrackWeights");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("CareerQuizQuestionId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("CareerQuizQuestionId");

                            b1.ToTable("CareerQuizQuestions");

                            b1
                                .ToJson("Text")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CareerQuizQuestionId");
                        });

                    b.Navigation("Options");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.CareerQuizSubmission", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Track", "RecommendedTrack")
                        .WithMany()
                        .HasForeignKey("RecommendedTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ItCareers.Domain.Entities.CareerQuizAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("CareerQuizSubmissionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("QuestionId");

                            b1.Property<int>("SelectedOptionIndex");

                            b1.HasKey("CareerQuizSubmissionId", "__synthesizedOrdinal");

                            b1.ToTable("CareerQuizSubmissions");

                            b1
                                .ToJson("Answers")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CareerQuizSubmissionId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("RecommendedTrack");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.FinalExamAttempt", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.FinalExamQuestion", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany("FinalExamQuestions")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ItCareers.Domain.Entities.QuizOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("FinalExamQuestionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsCorrect");

                            b1.HasKey("FinalExamQuestionId", "__synthesizedOrdinal");

                            b1.ToTable("FinalExamQuestions");

                            b1
                                .ToJson("Options")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FinalExamQuestionId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b2 =>
                                {
                                    b2.Property<Guid>("QuizOptionFinalExamQuestionId");

                                    b2.Property<int>("QuizOption__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("QuizOptionFinalExamQuestionId", "QuizOption__synthesizedOrdinal");

                                    b2.ToTable("FinalExamQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("QuizOptionFinalExamQuestionId", "QuizOption__synthesizedOrdinal");
                                });

                            b1.Navigation("Text")
                                .IsRequired();
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("FinalExamQuestionId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("FinalExamQuestionId");

                            b1.ToTable("FinalExamQuestions");

                            b1
                                .ToJson("Text")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FinalExamQuestionId");
                        });

                    b.Navigation("Options");

                    b.Navigation("Roadmap");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany("Phases")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Explanation", b1 =>
                        {
                            b1.Property<Guid>("PhaseId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("PhaseId");

                            b1.ToTable("Phases");

                            b1
                                .ToJson("Explanation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PhaseId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Tag", b1 =>
                        {
                            b1.Property<Guid>("PhaseId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("PhaseId");

                            b1.ToTable("Phases");

                            b1
                                .ToJson("Tag")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PhaseId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("PhaseId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("PhaseId");

                            b1.ToTable("Phases");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PhaseId");
                        });

                    b.Navigation("Explanation")
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("Tag");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.PhaseCompletion", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Project", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("Projects")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ProjectId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ItCareers.Domain.Entities.QuizOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("QuizQuestionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsCorrect");

                            b1.HasKey("QuizQuestionId", "__synthesizedOrdinal");

                            b1.ToTable("QuizQuestions");

                            b1
                                .ToJson("Options")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuizQuestionId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b2 =>
                                {
                                    b2.Property<Guid>("QuizOptionQuizQuestionId");

                                    b2.Property<int>("QuizOption__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("QuizOptionQuizQuestionId", "QuizOption__synthesizedOrdinal");

                                    b2.ToTable("QuizQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("QuizOptionQuizQuestionId", "QuizOption__synthesizedOrdinal");
                                });

                            b1.Navigation("Text")
                                .IsRequired();
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("QuizQuestionId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("QuizQuestionId");

                            b1.ToTable("QuizQuestions");

                            b1
                                .ToJson("Text")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuizQuestionId");
                        });

                    b.Navigation("Options");

                    b.Navigation("Phase");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Resource", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("Resources")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ResourceId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("Phase");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Track", "Track")
                        .WithMany("Roadmaps")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("RoadmapId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("RoadmapId");

                            b1.ToTable("Roadmaps");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Level", b1 =>
                        {
                            b1.Property<Guid>("RoadmapId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("RoadmapId");

                            b1.ToTable("Roadmaps");

                            b1
                                .ToJson("Level")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.OwnsMany("ItCareers.Domain.Common.LocalizedText", "Outcomes", b1 =>
                        {
                            b1.Property<Guid>("RoadmapId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("RoadmapId", "__synthesizedOrdinal");

                            b1.ToTable("Roadmaps");

                            b1
                                .ToJson("Outcomes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("RoadmapId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("RoadmapId");

                            b1.ToTable("Roadmaps");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Level");

                    b.Navigation("Outcomes");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Specialization", b =>
                {
                    b.OwnsMany("ItCareers.Domain.Common.SpecializationFaq", "Faqs", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.HasKey("SpecializationId", "__synthesizedOrdinal");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("Faqs")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Answer", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationFaqSpecializationId");

                                    b2.Property<int>("SpecializationFaq__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("SpecializationFaqSpecializationId", "SpecializationFaq__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationFaqSpecializationId", "SpecializationFaq__synthesizedOrdinal");
                                });

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Question", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationFaqSpecializationId");

                                    b2.Property<int>("SpecializationFaq__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("SpecializationFaqSpecializationId", "SpecializationFaq__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationFaqSpecializationId", "SpecializationFaq__synthesizedOrdinal");
                                });

                            b1.Navigation("Answer")
                                .IsRequired();

                            b1.Navigation("Question")
                                .IsRequired();
                        });

                    b.OwnsMany("ItCareers.Domain.Common.SpecializationSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("Enabled");

                            b1.Property<string>("ImageUrl");

                            b1.Property<int>("Key");

                            b1.HasKey("SpecializationId", "__synthesizedOrdinal");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("Sections")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Body", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationSectionSpecializationId");

                                    b2.Property<int>("SpecializationSection__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");
                                });

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "ImageCaption", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationSectionSpecializationId");

                                    b2.Property<int>("SpecializationSection__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");
                                });

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationSectionSpecializationId");

                                    b2.Property<int>("SpecializationSection__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");
                                });

                            b1.OwnsMany("ItCareers.Domain.Common.SpecializationSectionItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("SpecializationSectionSpecializationId");

                                    b2.Property<int>("SpecializationSection__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.HasKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Specializations");

                                    b2.WithOwner()
                                        .HasForeignKey("SpecializationSectionSpecializationId", "SpecializationSection__synthesizedOrdinal");

                                    b2.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Body", b3 =>
                                        {
                                            b3.Property<Guid>("SpecializationSectionItemSpecializationSectionSpecializationId");

                                            b3.Property<int>("SpecializationSectionItemSpecializationSection__synthesizedOrdinal")
                                                .HasColumnName("SpecializationSectionItemSpecializationSection__synthesizedOrd~");

                                            b3.Property<int>("SpecializationSectionItem__synthesizedOrdinal");

                                            b3.Property<string>("Ar")
                                                .IsRequired();

                                            b3.Property<string>("En")
                                                .IsRequired();

                                            b3.HasKey("SpecializationSectionItemSpecializationSectionSpecializationId", "SpecializationSectionItemSpecializationSection__synthesizedOrdinal", "SpecializationSectionItem__synthesizedOrdinal");

                                            b3.ToTable("Specializations");

                                            b3.WithOwner()
                                                .HasForeignKey("SpecializationSectionItemSpecializationSectionSpecializationId", "SpecializationSectionItemSpecializationSection__synthesizedOrdinal", "SpecializationSectionItem__synthesizedOrdinal");
                                        });

                                    b2.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b3 =>
                                        {
                                            b3.Property<Guid>("SpecializationSectionItemSpecializationSectionSpecializationId");

                                            b3.Property<int>("SpecializationSectionItemSpecializationSection__synthesizedOrdinal")
                                                .HasColumnName("SpecializationSectionItemSpecializationSection__synthesizedOrd~");

                                            b3.Property<int>("SpecializationSectionItem__synthesizedOrdinal");

                                            b3.Property<string>("Ar")
                                                .IsRequired();

                                            b3.Property<string>("En")
                                                .IsRequired();

                                            b3.HasKey("SpecializationSectionItemSpecializationSectionSpecializationId", "SpecializationSectionItemSpecializationSection__synthesizedOrdinal", "SpecializationSectionItem__synthesizedOrdinal");

                                            b3.ToTable("Specializations");

                                            b3.WithOwner()
                                                .HasForeignKey("SpecializationSectionItemSpecializationSectionSpecializationId", "SpecializationSectionItemSpecializationSection__synthesizedOrdinal", "SpecializationSectionItem__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Body")
                                        .IsRequired();

                                    b2.Navigation("Title")
                                        .IsRequired();
                                });

                            b1.Navigation("Body")
                                .IsRequired();

                            b1.Navigation("ImageCaption");

                            b1.Navigation("Items");

                            b1.Navigation("Title")
                                .IsRequired();
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "CardSentence", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("CardSentence")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "DemandQuickFact", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("DemandQuickFact")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "DifficultyQuickFact", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("DifficultyQuickFact")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "IntroVideoCaption", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("IntroVideoCaption")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "RoadmapButtonText", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("RoadmapButtonText")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "SalaryQuickFact", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("SalaryQuickFact")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Summary", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("Summary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "TimeToJobQuickFact", b1 =>
                        {
                            b1.Property<Guid>("SpecializationId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("SpecializationId");

                            b1.ToTable("Specializations");

                            b1
                                .ToJson("TimeToJobQuickFact")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SpecializationId");
                        });

                    b.Navigation("CardSentence")
                        .IsRequired();

                    b.Navigation("DemandQuickFact");

                    b.Navigation("DifficultyQuickFact");

                    b.Navigation("Faqs");

                    b.Navigation("IntroVideoCaption");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RoadmapButtonText");

                    b.Navigation("SalaryQuickFact");

                    b.Navigation("Sections");

                    b.Navigation("Summary")
                        .IsRequired();

                    b.Navigation("TimeToJobQuickFact");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TrackId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TrackId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("QuizQuestions");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.Navigation("FinalExamQuestions");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
