// <auto-generated />
using System;
using ItCareers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItCareers.Infrastructure.Migrations
{
    [DbContext(typeof(ItCareersDbContext))]
    [Migration("20260805053136_AddQuizQuestionsAndPhaseCompletions")]
    partial class AddQuizQuestionsAndPhaseCompletions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItCareers.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaddleTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaddleTransactionId")
                        .IsUnique();

                    b.HasIndex("RoadmapId");

                    b.HasIndex("UserId", "RoadmapId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("PhaseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.PhaseCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("UserId", "PhaseId")
                        .IsUnique();

                    b.ToTable("PhaseCompletions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCapstone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PaddlePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TrackId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany("Phases")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Explanation", b1 =>
                        {
                            b1.Property<Guid>("PhaseId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("PhaseId");

                            b1.ToTable("Phases");

                            b1
                                .ToJson("Explanation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PhaseId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("PhaseId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("PhaseId");

                            b1.ToTable("Phases");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PhaseId");
                        });

                    b.Navigation("Explanation")
                        .IsRequired();

                    b.Navigation("Roadmap");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.PhaseCompletion", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Project", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("Projects")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("ProjectId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ProjectId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ItCareers.Domain.Entities.QuizOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("QuizQuestionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsCorrect");

                            b1.HasKey("QuizQuestionId", "__synthesizedOrdinal");

                            b1.ToTable("QuizQuestions");

                            b1
                                .ToJson("Options")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuizQuestionId");

                            b1.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b2 =>
                                {
                                    b2.Property<Guid>("QuizOptionQuizQuestionId");

                                    b2.Property<int>("QuizOption__synthesizedOrdinal");

                                    b2.Property<string>("Ar")
                                        .IsRequired();

                                    b2.Property<string>("En")
                                        .IsRequired();

                                    b2.HasKey("QuizOptionQuizQuestionId", "QuizOption__synthesizedOrdinal");

                                    b2.ToTable("QuizQuestions");

                                    b2.WithOwner()
                                        .HasForeignKey("QuizOptionQuizQuestionId", "QuizOption__synthesizedOrdinal");
                                });

                            b1.Navigation("Text")
                                .IsRequired();
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<Guid>("QuizQuestionId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("QuizQuestionId");

                            b1.ToTable("QuizQuestions");

                            b1
                                .ToJson("Text")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuizQuestionId");
                        });

                    b.Navigation("Options");

                    b.Navigation("Phase");

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Resource", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Phase", "Phase")
                        .WithMany("Resources")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("ResourceId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("ResourceId");

                            b1.ToTable("Resources");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ResourceId");
                        });

                    b.Navigation("Phase");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.HasOne("ItCareers.Domain.Entities.Track", "Track")
                        .WithMany("Roadmaps")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<Guid>("RoadmapId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("RoadmapId");

                            b1.ToTable("Roadmaps");

                            b1
                                .ToJson("Title")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoadmapId");
                        });

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("TrackId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1
                                .ToJson("Description")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.OwnsOne("ItCareers.Domain.Common.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<Guid>("TrackId");

                            b1.Property<string>("Ar")
                                .IsRequired();

                            b1.Property<string>("En")
                                .IsRequired();

                            b1.HasKey("TrackId");

                            b1.ToTable("Tracks");

                            b1
                                .ToJson("Name")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Phase", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("QuizQuestions");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Roadmap", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("ItCareers.Domain.Entities.Track", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
